services:
  site:
    build: .
    container_name: library-site
    ports:
      - "8091:8091"
    restart: no
    networks:
      - library-network


networks:
  library-network:
    external: true
    name: library-network